global_costmap:
  global_frame: map
  robot_base_frame: body
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 1.0
  rolling_window: false 
  static_map: true 
  resolution: 0.05
  map_type: costmap