local_costmap:
  global_frame: odom
  robot_base_frame: body
  rolling_window: true
  static_map: false
  width: 3.0
  height: 3.0
  update_frequency: 10.0        # 原10.0
  publish_frequency: 10.0       # 原10.0
  transform_tolerance: 1.0



